### ISSUE TITLE
Documentation on how to initialize/authenticate on distributed cluster 

### ISSUE THREAD

**Issue by jterry64** [google/Xee#99]
When I try to run `xarray.open_dataset` with chunks set and an active distributed dask cluster, it correctly distributes the chunks to workers. But then it fails because each individual worker needs to ee.Initialize(). 

Is this a supported use case, and is there documentation or examples on how to set up the authentication/initialization across the whole cluster?

**Comment by naschmitz** [comment]
Thanks for your question, @jterry64.

We don't have any documentation or examples because running xee across a distributed cluster is something we haven't quite figured out ourselves yet.

As you probably know, the EE client libraries are a bit weird in the sense that methods are patched in after we've made a request to the EE backend. We're working on some changes to eliminate the need for initialization by statically shipping most methods with the Python client libraries, but they won't be ready until Q1 of next year. We'll update this issue and our documentation when those changes are released.

**Comment by alxmrs** [comment]
Nate, in the meantime: do you think it would be possible to make Initialize
pickleable? That may address the issues with both Dask and Beam.

**Comment by KMarkert** [comment]
I think there are two problems at play here: 1. initialization of the `ee` modules and 2. authorization for a worker to make EE calls. The static client library methods will only solve issue one and I am not sure how providing a pickled object will work for the authorized calls.

I think we can add in a check for when xee makes a call to EE if the module is initialized and if so then call `ee.Initialize()`. This can be a flag when creating a dataset to enable "auto initialize" which a user should only use for distributed jobs.

@naschmitz @alxmrs thoughts?

**Comment by noahgolmant** [comment]
@jterry64 the current implementation is already multithreaded, so not sure a LocalCluster will help things. Reading the dataset into numpy is parallelized with the `concurrent` module, and saving to zarr saves each chunk in parallel with a threaded Dask scheduler (which is the default behavior of xarray).

Multiprocessing on a local cluster fails because the EE initialized session data is not pickle-able, it is the same reason why the distributed version fails today I think? This still requires some RAM, since `computePixels` does materialize each chunk's data on the machine before saving it to zarr.

**Comment by ljstrnadiii** [comment]
Even if we get earth sessions to pickle and dask to "work", are there any concerns with nested threading and keeping a hold on the number of requests per min?

Since dask workers use threading by default, and if each chunk then uses the concurrent threading module to make the computePixel call, then it might be a bit hard to manage the number of requests since dask doesn't directly support a maximum number of tasks, etc.

**Comment by alxmrs** [comment]
I haven’t tested this out on Dask, but I do have experience running it with
xbeam. This is also a multi-threaded, concurrent environment (it uses Dask
threads, Beam/Dataflow VMs, and concurrent.futures). Xee works here (and
should on a Dask cluster) since it implements retries with exponential
backoff.

The cost is that we find out late when a pipeline has a logical error, but
the benefit is that we get all the data in a parallel way without explicit
throttling.

**Comment by ljstrnadiii** [comment]
Makes sense! I didn't know dask threads are used with xbeam--havent used it yet.

I have definitely hit limits where even with retries and exponential back off it fails due to longer running ee tasks like calling median over an image collection or hitting our number of concurrent connection quota or number of read requests quota. It's hard to know in advance how far you can push these limits as I'm sure you already know!

I try to control for that with large spatial mosaics by first calling to_zarr with compute=False and then submitting batches of chunks using to_zarr with region={...} where the number of batches is tuned per dataset to a number that does not seem to put too much pressure on our quotas. Submitting these tasks to dask or flyte or beam with some sort of dynamic concurrency might be the most robust, but sounds rather complicated.

Another small thing that could possibly help is the TODO of surfacing the pool size arg as a backend arg for the ThreadExecutor. I am considering picking up that task!

**Comment by naschmitz** [comment]
I'm going to close this discussion since we've put out an [example](https://github.com/google/Xee/blob/main/examples/dataflow/ee_to_zarr_dataflow.py) running an Xee pipeline on Dataflow.
